{{- include "k8s-spark-ui-assist.validateGateway" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-spark-ui-assist.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-spark-ui-assist.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-spark-ui-assist.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-spark-ui-assist.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "k8s-spark-ui-assist.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: spark-ui-assist
          image: {{ include "k8s-spark-ui-assist.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["/spark-ui-assist"]
          args:
            - -http-route.hostname={{ include "k8s-spark-ui-assist.httpHostname" . }}
            - -http-route.gateway-name={{ include "k8s-spark-ui-assist.httpGatewayName" . }}
            - -http-route.gateway-namespace={{ include "k8s-spark-ui-assist.httpGatewayNamespace" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
